### ISSUE TITLE
Shunting unload jobs spawning with more drop offs than cars. Game is prevented from saving after this happens

### ISSUE THREAD

**Issue by ben-vanderlinde** [Banjobeni/DerailValley-PersistentJobs#4]
Hi, thanks for a great mod I enjoy it.

I've noticed the following issue :

Sometimes shunting unload jobs spawn with more drop offs than cars.
![image](https://github.com/Banjobeni/DerailValley-PersistentJobs/assets/71764990/63fef089-a884-45d0-a767-ec42bc795dc9)
![image](https://github.com/Banjobeni/DerailValley-PersistentJobs/assets/71764990/963e67ee-5c7a-4643-a83e-ff70dee6c552)

In my case a single car was assigned to a job with three drop offs.
Once the job spawns the game can no longer be saved. When saving the console shows the error :
Saving Manual failed: "Couldn't extract carGuidsPerDestinationTrack"
![image](https://github.com/Banjobeni/DerailValley-PersistentJobs/assets/71764990/59bfe399-640e-4c6a-a436-06ca2852d6e9)

If I accept the job, I cannot complete it, but if I bin the job after accepting it immediately I am able to save again.

After leaving MF with another job, the troublesome job spawns again, and prevents saving. This time I cannot accept the job. The job machine makes the job denied sound (fees have been cleared), but no reason is printed.
The save game issue is then resolved by clearing all the cars attached to this job.

The exception & stack trace I found in the player.log is:
Exception: Couldn't extract carGuidsPerDestinationTrack
  at StaticShuntingUnloadJobDefinition.GetJobDefinitionSaveData () [0x0012e] in <4dd6bf05cc8c4e4288a4683024f156b0>:0 
  at JobChainController.GetJobChainSaveData () [0x00059] in <4dd6bf05cc8c4e4288a4683024f156b0>:0 
  at JobSaveManager.GetJobsSaveGameData () [0x00028] in <4dd6bf05cc8c4e4288a4683024f156b0>:0 
  at SaveGameManager.UpdateInternalData () [0x001bb] in <4dd6bf05cc8c4e4288a4683024f156b0>:0 
  at (wrapper dynamic-method) SaveGameManager.SaveGameManager.Save_Patch1(SaveGameManager,DV.Common.SaveType,DV.Common.ISaveGame)
  at DV.UI.UserProfileProvider.SaveGame (DV.Common.SaveType type) [0x00005] in <4dd6bf05cc8c4e4288a4683024f156b0>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
DV.UI.UserProfileProvider:SaveGame(SaveType)
DV.UI.SaveLoadController:OnSaveClicked()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
DV.UIFramework.ButtonDV:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

Attached is the full log:
[Player.zip](https://github.com/Banjobeni/DerailValley-PersistentJobs/files/12517987/Player.zip)

**Comment by Banjobeni** [comment]
Hi, many thanks for the bug report. I will look into it, but I need some more information:
/

**Comment by Banjobeni** [comment]
Thank you for the detailed explanation. The save will do, I will look into it.

Regarding some points that you mention, for clarification:
* For shunt jobs, the cars must not be on the warehouse (L) track already. That is a deliberate feature of the mod. I opened #5 in order to help make that more obvious
* When new jobs spawn for cars after completing another job, we need to distinguish:
  * (a) regular job chains SL-FH-SU: Those are (should be, see #2) generated immediately after turning the current job in. This should behave more or less like vanilla
  * reuse of cars after SU, LH oder any other way of bringing cars in making them jobless: This is what I call the cars reuse algorithm, and it *currently* runs on two occasions:
     * (b) Leaving the station. Each minute or so, the mod checks for jobless cars in all stations excpt where the player currently is, and tries to come up with jobs for those cars
     * (c) taking fast travel to anywhere else: This will immediately trigger jobs generation for all (i think) jobless cars

For (a), it should never be the case that less cars are used for the subsequent part, i.e. the total number of cars for SL, subsequent FH, subsequent SU should always be the same.

For (b) and (c), there should be no difference in behaviour regarding splitting of a consist.

While you are inside a station and not fast traveling, aside from normal job chain job generation (a), jobless cars should **never** be reallocated to new jobs. If you see that happen, I need to look into it.

**Comment by Banjobeni** [comment]
So it seems the shunting unload generator never really paid attention to the number of cars possibly being smaller than the targetted number of tracks. I'm just clamping the max. number of tracks to the number of cars now. I split up the consist in MF-C1L into 4 pieces, one waggon each, and this is the result after new jobs are generated.

![grafik](https://github.com/Banjobeni/DerailValley-PersistentJobs/assets/8106744/3e7a22f0-a9ab-4906-ac61-1d02d1969933)

I guess that fixes it, and the fix will be in the next release.
